import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import { BarChart, Bar, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import * as api from '../../api/adminApi'
import { ErrorState, EmptyState } from '../../components/common/QueryFeedback'
import ModalFocusRegion from '../../components/common/ModalFocusRegion'

const money = (n) => `$${(n / 100).toFixed(2)}`
function Shell({ title, eyebrow, children }) { return <section><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-700">{eyebrow}</p><h1 className="mt-2 text-3xl font-bold text-slate-950 sm:text-4xl">{title}</h1>{children}</section> }
function Pager({ meta, onPage }) { if (!meta || meta.totalPages <= 1) return null; return <div className="mt-5 flex items-center justify-between gap-3 text-sm text-slate-600"><button className="le-button le-button-secondary" disabled={meta.page <= 1} onClick={() => onPage(meta.page - 1)}>Previous</button><span>Page {meta.page} of {meta.totalPages}</span><button className="le-button le-button-secondary" disabled={meta.page >= meta.totalPages} onClick={() => onPage(meta.page + 1)}>Next</button></div> }
function ConfirmDialog({ item, onCancel, onConfirm, pending, error }) { if (!item) return null; return <ModalFocusRegion labelledBy="admin-confirm-title" onClose={onCancel} closeOnEscape={!pending} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl"><h2 id="admin-confirm-title" className="text-xl font-bold text-slate-950">{item.title}</h2><p className="mt-3 leading-6 text-slate-600">{item.description}</p>{error && <p role="alert" className="mt-3 text-sm text-rose-700">This action could not be completed.</p>}<div className="mt-6 flex flex-wrap justify-end gap-3"><button type="button" className="le-button le-button-secondary" disabled={pending} onClick={onCancel}>Cancel</button><button type="button" className={`le-button ${item.danger ? 'le-button-danger' : 'le-button-primary'}`} disabled={pending} onClick={onConfirm}>{pending ? 'Working…' : item.confirmLabel}</button></div></div></ModalFocusRegion> }

export function AdminUsersPage() {
  const qc = useQueryClient(); const [confirm, setConfirm] = useState(null); const [roleFilter, setRoleFilter] = useState(''); const [statusFilter, setStatusFilter] = useState(''); const [page,setPage]=useState(1); const params={...(roleFilter&&{role:roleFilter}),...(statusFilter&&{status:statusFilter}),page}; const query = useQuery({ queryKey: ['admin', 'users', params], queryFn: () => api.getAdminUsers(params) })
  const role = useMutation({ mutationFn: api.updateAdminUserRole, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin', 'users'] }); qc.invalidateQueries({ queryKey: ['admin', 'analytics'] }); setConfirm(null) } })
  const status = useMutation({ mutationFn: api.updateAdminUserStatus, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin', 'users'] }); qc.invalidateQueries({ queryKey: ['admin', 'analytics'] }); setConfirm(null) } })
  if (query.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />
  if (query.isError) return <ErrorState message="Users could not be loaded." onRetry={query.refetch} />
  const pending = role.isPending || status.isPending; const mutationError = role.isError || status.isError
  const apply = () => confirm.kind === 'role' ? role.mutate({ id: confirm.user.id, role: confirm.value }) : status.mutate({ id: confirm.user.id, status: confirm.value })
  return <Shell eyebrow="Administration" title="Manage users"><p className="mt-3 text-slate-600">Role and account-status changes take effect immediately and preserve historical records.</p><div className="mt-5 flex flex-wrap gap-3"><select value={roleFilter} onChange={e=>{setRoleFilter(e.target.value);setPage(1)}} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">All roles</option><option value="user">Users</option><option value="lawyer">Lawyers</option><option value="admin">Admins</option></select><select value={statusFilter} onChange={e=>{setStatusFilter(e.target.value);setPage(1)}} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">All statuses</option><option value="active">Active</option><option value="deactivated">Deactivated</option></select></div><div className="mt-5 grid gap-4">{query.data.items.map((user) => <article key={user.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div className="min-w-0"><h2 className="font-semibold text-slate-950">{user.fullName}</h2><p className="truncate text-sm text-slate-600">{user.email}</p><p className="mt-2 text-sm capitalize text-slate-500">{user.role} · {user.status}</p></div><div className="flex flex-wrap gap-2"><select aria-label={`Role for ${user.fullName}`} value={user.role} onChange={(event) => event.target.value !== user.role && setConfirm({ kind: 'role', user, value: event.target.value, title: `Change ${user.fullName}'s role?`, description: 'This changes what the account can access. A lawyer changed to a user is removed from public discovery.', confirmLabel: 'Change role' })} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="user">User</option><option value="lawyer">Lawyer</option><option value="admin">Admin</option></select><button className={`le-button ${user.status === 'active' ? 'le-button-danger' : 'le-button-primary'}`} onClick={() => setConfirm({ kind: 'status', user, value: user.status === 'active' ? 'deactivated' : 'active', title: `${user.status === 'active' ? 'Deactivate' : 'Activate'} ${user.fullName}?`, description: user.status === 'active' ? 'The account will immediately lose protected access. Historical records stay preserved.' : 'The account will regain protected access according to its current role.', confirmLabel: user.status === 'active' ? 'Deactivate account' : 'Activate account', danger: user.status === 'active' })}>{user.status === 'active' ? 'Deactivate' : 'Activate'}</button></div></div></article>)}</div><Pager meta={query.data.meta} onPage={setPage}/><ConfirmDialog item={confirm} onCancel={() => setConfirm(null)} onConfirm={apply} pending={pending} error={mutationError} /></Shell>
}

const actionsFor = (profile) => profile.publicationStatus === 'deleted' ? ['restore'] : profile.publicationStatus === 'published' ? ['unpublish', 'suspend'] : ['publish', 'suspend']
export function AdminLawyersPage() {
  const qc = useQueryClient(); const [confirm, setConfirm] = useState(null); const [publicationStatus,setPublicationStatus]=useState(''); const [page,setPage]=useState(1); const params={...(publicationStatus&&{publicationStatus}),page}; const query = useQuery({ queryKey: ['admin', 'lawyers', params], queryFn: () => api.getAdminLawyers(params) })
  const totalPages = query.data?.meta?.totalPages
  useEffect(() => {
    if (query.isFetching || !query.isSuccess || !Number.isInteger(totalPages)) return
    const lastPage = Math.max(1, totalPages)
    if (page > lastPage) setPage(lastPage)
  }, [page, query.isFetching, query.isSuccess, totalPages])
  const moderate = useMutation({ mutationFn: api.moderateAdminLawyer, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin', 'lawyers'] }); qc.invalidateQueries({ queryKey: ['admin', 'analytics'] }); qc.invalidateQueries({ queryKey: ['public-lawyers'] }); setConfirm(null) } })
  const remove = useMutation({ mutationFn: api.deleteAdminLawyer, onSuccess: () => { qc.invalidateQueries({ queryKey: ['admin', 'lawyers'] }); qc.invalidateQueries({ queryKey: ['public-lawyers'] }); setConfirm(null) } })
  if (query.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />
  if (query.isError) return <ErrorState message="Lawyer profiles could not be loaded." onRetry={query.refetch} />
  const pending = moderate.isPending || remove.isPending; const mutationError = moderate.isError || remove.isError
  const apply = () => confirm.kind === 'delete' ? remove.mutate(confirm.profile.id) : moderate.mutate({ id: confirm.profile.id, action: confirm.action })
  return <Shell eyebrow="Administration" title="Manage lawyers"><p className="mt-3 text-slate-600">Listing moderation never changes verified payment, paid-hire, or historical transaction records.</p><select value={publicationStatus} onChange={e=>{setPublicationStatus(e.target.value);setPage(1)}} className="mt-5 min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">All listing states</option>{['draft','published','unpublished','suspended','deleted'].map(s=><option key={s}>{s}</option>)}</select><div className="mt-5 grid gap-4">{query.data.items.map((profile) => <article key={profile.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">{profile.fullName}</h2><p className="text-sm text-slate-600">{profile.email} · {profile.specialization || 'No specialization'}</p><p className="mt-2 text-sm capitalize text-slate-500">{profile.publicationStatus} · verification {profile.verificationStatus}</p><div className="mt-4 flex flex-wrap gap-2">{actionsFor(profile).map((action) => <button key={action} className="le-button le-button-secondary capitalize" onClick={() => setConfirm({ kind: 'moderate', profile, action, title: `${action[0].toUpperCase()}${action.slice(1)} this lawyer profile?`, description: action === 'suspend' ? 'This removes the listing from public discovery until an admin changes its state.' : action === 'restore' ? 'The profile returns privately and will not become public automatically.' : 'The server will re-check eligibility before applying this publication action.', confirmLabel: action })}>{action}</button>)}{profile.publicationStatus !== 'deleted' && <button className="le-button le-button-danger" onClick={() => setConfirm({ kind: 'delete', profile, title: 'Soft-delete this lawyer profile?', description: 'It will be removed from public discovery. Hiring, payment, and comment history are preserved.', confirmLabel: 'Delete profile', danger: true })}>Delete profile</button>}</div></article>)}</div><Pager meta={query.data.meta} onPage={setPage}/><ConfirmDialog item={confirm} onCancel={() => setConfirm(null)} onConfirm={apply} pending={pending} error={mutationError} /></Shell>
}

export function AdminTransactionsPage() { const [type,setType]=useState(''); const [status,setStatus]=useState(''); const [page,setPage]=useState(1); const params={...(type&&{type}),...(status&&{status}),page}; const query = useQuery({ queryKey: ['admin', 'transactions',params], queryFn: () => api.getAdminTransactions(params) }); if (query.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />; if (query.isError) return <ErrorState message="Transactions could not be loaded." onRetry={query.refetch} />; return <Shell eyebrow="Financial records" title="All transactions"><p className="mt-3 text-slate-600">Read-only records. Payment state remains controlled by verified Stripe webhooks.</p><div className="mt-5 flex flex-wrap gap-3"><select value={type} onChange={e=>{setType(e.target.value);setPage(1)}} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">All types</option><option value="lawyer_verification">Verification</option><option value="hiring_fee">Hiring fee</option></select><select value={status} onChange={e=>{setStatus(e.target.value);setPage(1)}} className="min-h-11 rounded-xl border border-slate-300 bg-white px-3"><option value="">All statuses</option>{['pending','paid','failed','refunded'].map(s=><option key={s}>{s}</option>)}</select></div>{query.data.items.length ? <div className="mt-5 grid gap-3">{query.data.items.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5"><p className="font-semibold capitalize text-slate-950">{item.type.replace('_', ' ')}</p><p className="mt-1 break-words text-sm text-slate-600">{item.payer?.email || 'Unavailable'} → {item.lawyer?.email || 'Unavailable'}</p><p className="mt-2 font-semibold text-slate-950">{money(item.amountMinor)} {item.currency.toUpperCase()} · {item.status}</p></article>)}</div> : <div className="mt-7"><EmptyState title="No transactions" description="Verified payment records will appear here." /></div>}<Pager meta={query.data.meta} onPage={setPage}/></Shell> }

export function AdminAnalyticsPage() { const query = useQuery({ queryKey: ['admin', 'analytics'], queryFn: api.getAdminAnalytics }); if (query.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />; if (query.isError) return <ErrorState message="Analytics could not be loaded." onRetry={query.refetch} />; const cards = [['Total users', query.data.users], ['Total lawyers', query.data.lawyers], ['Total paid hires', query.data.paidHires], ['Verified revenue', money(query.data.revenueMinor)]]; return <Shell eyebrow="Live aggregation" title="Analytics"><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p></article>)}</div><div className="mt-6 grid gap-5 lg:grid-cols-2"><Chart title="Monthly verified revenue" data={query.data.monthlyRevenue} value="revenueMinor" /><Chart title="Monthly paid hires" data={query.data.monthlyHires} value="paidHires" /></div></Shell> }
function Chart({ title, data, value }) { return <article className="h-72 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">{title}</h2>{data.length ? <ResponsiveContainer width="100%" height="90%"><BarChart data={data}><XAxis dataKey="month" /><YAxis /><Tooltip /><Bar dataKey={value} fill="#4338ca" radius={[6, 6, 0, 0]} /></BarChart></ResponsiveContainer> : <p className="grid h-[85%] place-items-center text-sm text-slate-500">No verified activity yet.</p>}</article> }
