import { useMutation, useQuery } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { getMyHiringRequests } from '../../api/hiringRequestApi'
import { startHiringCheckout } from '../../api/paymentApi'
import ProfileAvatar from '../../components/common/ProfileAvatar'
import { ErrorState } from '../../components/common/QueryFeedback'
import { getApiErrorMessage } from '../../utils/apiError'

function date(value) { return value ? new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(value)) : null }
function paymentLabel(status) { return status === 'paid' ? 'Paid' : status === 'checkout_created' ? 'Payment session ready' : 'Unpaid' }

export default function UserHiringHistoryPage() {
  const requests = useQuery({ queryKey: ['hiring-requests', 'mine'], queryFn: getMyHiringRequests })
  const pay = useMutation({ mutationFn: startHiringCheckout, onSuccess: ({ checkoutUrl }) => window.location.assign(checkoutUrl) })
  if (requests.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />
  if (requests.isError) return <ErrorState message={getApiErrorMessage(requests.error)} onRetry={() => requests.refetch()} />

  return <section><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-700">Your legal matters</p><h1 className="mt-2 text-3xl font-bold tracking-tight text-slate-950 sm:text-4xl">My hiring requests</h1><p className="mt-3 max-w-2xl text-slate-600">Requests you sent to lawyers. A payment becomes available only after that lawyer accepts.</p>{requests.data.length === 0 ? <div className="mt-7 rounded-2xl border border-slate-200 bg-white p-6 text-slate-600">You have not sent a hiring request yet.</div> : <div className="mt-7 grid gap-4">{requests.data.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex min-w-0 items-center gap-4"><ProfileAvatar src={item.lawyer.professionalPhotoUrl} name={item.lawyer.fullName} alt={`Portrait of ${item.lawyer.fullName}`} className="h-16 w-16" textClassName="text-lg" /><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-[0.14em] text-slate-500">Lawyer</p><h2 className="mt-1 truncate text-lg font-semibold text-slate-950">{item.lawyer.fullName}</h2><p className="mt-1 text-sm text-slate-600">{item.specializationSnapshot} · ${(item.feeMinorSnapshot / 100).toFixed(2)} {item.currency}</p><p className="mt-2 text-xs text-slate-500">Requested {date(item.createdAt)}{item.paidAt ? ` · Paid ${date(item.paidAt)}` : ''}</p></div></div><div className="mt-5 flex flex-wrap items-center gap-2 border-t border-slate-100 pt-4"><span className="rounded-full bg-indigo-50 px-3 py-1 font-semibold capitalize text-indigo-800">Request: {item.status}</span><span className={`rounded-full px-3 py-1 font-semibold ${item.paymentStatus === 'paid' ? 'bg-emerald-50 text-emerald-800' : 'bg-slate-100 text-slate-700'}`}>Payment: {paymentLabel(item.paymentStatus)}</span>{item.status === 'accepted' && item.paymentStatus !== 'paid' && <button type="button" disabled={pay.isPending} onClick={() => pay.mutate(item.id)} className="min-h-11 whitespace-nowrap rounded-xl bg-indigo-700 px-4 font-semibold text-white disabled:opacity-60">{pay.isPending ? 'Opening…' : item.paymentStatus === 'checkout_created' ? 'Continue secure payment' : 'Pay consultation fee'}</button>}<Link to={`/lawyers/${item.lawyerProfileId}`} className="inline-flex min-h-11 items-center whitespace-nowrap rounded-xl border border-indigo-200 bg-indigo-50 px-4 py-2 font-semibold text-indigo-800 transition hover:border-indigo-700 hover:bg-indigo-700 hover:text-white">View lawyer</Link>{pay.isError && <p role="alert" className="basis-full text-sm text-rose-700">{getApiErrorMessage(pay.error)}</p>}</div></article>)}</div>}</section>
}
