import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { useState } from 'react'
import { deleteComment, getMyComments, updateComment } from '../../api/commentApi'
import ModalFocusRegion from '../../components/common/ModalFocusRegion'
import { EmptyState, ErrorState } from '../../components/common/QueryFeedback'
import { getApiErrorMessage } from '../../utils/apiError'

function EditDialog({ content, edit, onCancel, onContent }) {
  return <ModalFocusRegion labelledBy="edit-comment-title" onClose={onCancel} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={(event) => { event.preventDefault(); edit.mutate() }} className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 id="edit-comment-title" className="text-xl font-bold">Edit comment</h2><textarea value={content} onChange={(event) => onContent(event.target.value)} minLength={2} maxLength={1000} required className="mt-4 min-h-32 w-full rounded-xl border border-slate-300 p-3" /><div className="mt-4 flex justify-end gap-3"><button type="button" className="le-button le-button-secondary" onClick={onCancel}>Cancel</button><button type="submit" className="le-button le-button-primary" disabled={edit.isPending}>{edit.isPending ? 'Saving…' : 'Save changes'}</button></div>{edit.isError && <p role="alert" className="mt-3 text-sm text-rose-700">{getApiErrorMessage(edit.error)}</p>}</form></ModalFocusRegion>
}

function DeleteDialog({ pending, onCancel, onConfirm }) {
  return <ModalFocusRegion labelledBy="delete-comment-title" onClose={onCancel} className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><h2 id="delete-comment-title" className="text-xl font-bold">Delete this comment?</h2><p className="mt-2 text-slate-600">This removes it from the public lawyer profile.</p><div className="mt-5 flex justify-end gap-3"><button type="button" className="le-button le-button-secondary" onClick={onCancel}>Cancel</button><button type="button" className="le-button le-button-danger" disabled={pending} onClick={onConfirm}>Delete</button></div></div></ModalFocusRegion>
}

export default function UserCommentsPage() {
  const qc = useQueryClient(); const query = useQuery({ queryKey: ['comments', 'mine'], queryFn: getMyComments }); const [editItem, setEditItem] = useState(null); const [content, setContent] = useState(''); const [deleteItem, setDeleteItem] = useState(null)
  const refresh = () => qc.invalidateQueries({ queryKey: ['comments', 'mine'] }); const edit = useMutation({ mutationFn: () => updateComment(editItem.id, content), onSuccess: () => { refresh(); qc.invalidateQueries({ queryKey: ['lawyerComments', editItem.lawyerProfileId] }); setEditItem(null) } }); const remove = useMutation({ mutationFn: deleteComment, onSuccess: () => { refresh(); qc.invalidateQueries({ queryKey: ['lawyerComments', deleteItem.lawyerProfileId] }); setDeleteItem(null) } })
  if (query.isLoading) return <div className="h-64 animate-pulse rounded-2xl bg-slate-200" />
  if (query.isError) return <ErrorState message={getApiErrorMessage(query.error)} onRetry={() => query.refetch()} />
  return <section><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-700">Your feedback</p><h1 className="mt-2 text-3xl font-bold text-slate-950 sm:text-4xl">My comments</h1><p className="mt-3 text-slate-600">Manage comments submitted after verified paid hires.</p>{query.data.length === 0 ? <div className="mt-7"><EmptyState title="No comments yet" description="After an accepted and paid hire, you can share one comment on that lawyer’s profile." /></div> : <div className="mt-7 grid gap-4">{query.data.map((item) => <article key={item.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-semibold text-slate-950">{item.lawyer?.fullName || 'Lawyer profile unavailable'}</h2><p className="mt-1 text-sm text-slate-500">{item.lawyer?.specialization || 'Professional profile unavailable'}</p><p className="mt-4 whitespace-pre-wrap text-slate-700">{item.content}</p><div className="mt-5 flex flex-wrap gap-3"><button type="button" className="le-button le-button-secondary" onClick={() => { setEditItem(item); setContent(item.content) }}>Edit comment</button><button type="button" className="le-button le-button-danger" onClick={() => setDeleteItem(item)}>Delete comment</button></div></article>)}</div>}{editItem && <EditDialog content={content} edit={edit} onCancel={() => setEditItem(null)} onContent={setContent} />}{deleteItem && <DeleteDialog pending={remove.isPending} onCancel={() => setDeleteItem(null)} onConfirm={() => remove.mutate(deleteItem.id)} />}</section>
}
