import { useMutation, useQueryClient } from '@tanstack/react-query'
import { X } from 'lucide-react'
import { createHiringRequest } from '../../api/hiringRequestApi'
import { getApiErrorMessage } from '../../utils/apiError'

export default function HireModal({ lawyer, onClose }) {
  const client = useQueryClient()
  const request = useMutation({ mutationFn: () => createHiringRequest(lawyer.id), onSuccess: () => { client.invalidateQueries({ queryKey: ['hiring-requests', 'mine'] }); onClose() } })
  return <div role="dialog" aria-modal="true" aria-labelledby="hire-modal-title" className="fixed inset-0 z-50 grid place-items-center bg-slate-950/50 p-4"><section className="w-full max-w-md rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-indigo-700">Hiring request</p><h2 id="hire-modal-title" className="mt-2 text-2xl font-bold text-slate-950">Hire Legal Counsel</h2></div><button type="button" onClick={onClose} disabled={request.isPending} aria-label="Close hire confirmation" className="grid min-h-11 min-w-11 place-items-center rounded-lg text-slate-700 hover:bg-slate-100"><X /></button></div><dl className="mt-6 space-y-3 rounded-xl bg-slate-50 p-4 text-sm"><div><dt className="text-slate-500">Lawyer</dt><dd className="font-semibold text-slate-950">{lawyer.fullName}</dd></div><div><dt className="text-slate-500">Specialization</dt><dd className="font-semibold text-slate-950">{lawyer.specialization}</dd></div><div><dt className="text-slate-500">Consultation fee</dt><dd className="font-semibold text-slate-950">${(lawyer.consultationFeeMinor / 100).toFixed(2)} USD</dd></div><div><dt className="text-slate-500">Availability</dt><dd className="font-semibold capitalize text-emerald-700">{lawyer.availability}</dd></div></dl><p className="mt-4 text-sm text-slate-600">The lawyer reviews this request first. If accepted, you can pay securely from My hiring requests.</p>{request.isError && <p role="alert" className="mt-3 text-sm text-rose-700">{getApiErrorMessage(request.error)}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose} disabled={request.isPending} className="min-h-11 rounded-lg px-4 text-sm font-semibold text-slate-700">Cancel</button><button type="button" onClick={() => request.mutate()} disabled={request.isPending} className="min-h-11 rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white disabled:opacity-60">{request.isPending ? 'Sending…' : 'Send hiring request'}</button></div></section></div>
}
