import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Link } from 'react-router-dom'
import { useState } from 'react'
import { createLawyerComment, getLawyerComments } from '../../api/commentApi'
import { ErrorState, EmptyState } from '../common/QueryFeedback'
import { getApiErrorMessage } from '../../utils/apiError'
const when = (v) => new Intl.DateTimeFormat('en', { dateStyle: 'medium' }).format(new Date(v))
export default function LawyerComments({ profileId, canComment, hasComment, isAuthenticated, role }) {
  const qc = useQueryClient(); const [content, setContent] = useState(''); const query = useQuery({ queryKey: ['lawyerComments', profileId], queryFn: () => getLawyerComments(profileId) })
  const create = useMutation({ mutationFn: () => createLawyerComment(profileId, content), onSuccess: () => { setContent(''); qc.invalidateQueries({ queryKey: ['lawyerComments', profileId] }); qc.invalidateQueries({ queryKey: ['comments', 'mine'] }) } })
  return <section className="mt-10 border-t border-slate-200 pt-8"><p className="text-xs font-bold uppercase tracking-[.18em] text-indigo-700">Client comments</p><h2 className="mt-2 text-2xl font-bold text-slate-950">Experiences from verified clients</h2>{query.isLoading ? <div className="mt-5 h-28 animate-pulse rounded-2xl bg-slate-200" /> : query.isError ? <div className="mt-5"><ErrorState message={getApiErrorMessage(query.error)} onRetry={() => query.refetch()} /></div> : query.data.length ? <div className="mt-5 grid gap-3">{query.data.map((c) => <article key={c.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="font-semibold text-slate-950">{c.author.fullName}</p><p className="mt-2 whitespace-pre-wrap leading-7 text-slate-700">{c.content}</p><p className="mt-3 text-xs text-slate-500">{c.updatedAt !== c.createdAt ? `Updated ${when(c.updatedAt)}` : when(c.createdAt)}</p></article>)}</div> : <div className="mt-5"><EmptyState title="No client comments yet" description="Verified client experiences will appear here." /></div>}<div className="mt-6 rounded-2xl bg-indigo-50 p-5">{canComment && !hasComment ? <form onSubmit={(e) => { e.preventDefault(); if (content.trim()) create.mutate() }}><label className="font-semibold" htmlFor="comment">Share your experience</label><textarea id="comment" value={content} onChange={(e) => setContent(e.target.value)} minLength={2} maxLength={1000} required className="mt-3 min-h-28 w-full rounded-xl border border-indigo-200 bg-white p-3" placeholder="Write a plain-text comment about your experience." /><div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-500">{content.length}/1000</span><button className="le-button le-button-primary" disabled={create.isPending}>{create.isPending ? 'Submitting…' : 'Submit comment'}</button></div>{create.isError && <p className="mt-3 text-sm text-rose-700">{getApiErrorMessage(create.error)}</p>}</form> : hasComment ? <p className="text-sm text-indigo-950">You have already commented. <Link className="font-semibold underline" to="/dashboard/user/comments">Manage your comment</Link>.</p> : !isAuthenticated ? <p className="text-sm text-indigo-950">Sign in after a paid hire to share your experience.</p> : role === 'user' ? <p className="text-sm text-indigo-950">Only clients with an accepted, paid hire can comment.</p> : <p className="text-sm text-indigo-950">Comments are available for verified client experiences.</p>}</div></section>
}
