import { useMutation, useQueryClient } from '@tanstack/react-query'
import { BadgeCheck, CircleAlert, CreditCard, Eye, EyeOff } from 'lucide-react'
import { changePublication, startVerificationCheckout } from '../../api/paymentApi'
import { getApiErrorMessage } from '../../utils/apiError'
import { showSuccessToast } from '../../utils/toast'

export default function VerificationPublishingPanel({ profile }) {
  const client = useQueryClient()
  const refresh = () => client.invalidateQueries({ queryKey: ['lawyer-profile', 'me'] })
  const checkout = useMutation({ mutationFn: startVerificationCheckout, onSuccess: ({ checkoutUrl }) => { window.location.assign(checkoutUrl) } })
  const publication = useMutation({ mutationFn: changePublication, onSuccess: () => { refresh(); showSuccessToast('Demo email notification queued for your publishing update.') } })
  const fee = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(profile.publishingFeeMinor / 100)
  const locked = ['suspended', 'deleted'].includes(profile.publicationStatus)
  const message = checkout.isError ? getApiErrorMessage(checkout.error) : publication.isError ? getApiErrorMessage(publication.error) : ''
  return <section className="rounded-xl border border-indigo-200 bg-indigo-50/60 p-5"><div className="flex gap-3"><BadgeCheck className="mt-1 text-indigo-700" size={22} /><div><h3 className="text-lg font-semibold text-slate-950">Verification &amp; Publishing</h3><p className="mt-1 text-sm leading-6 text-slate-700">Payment verifies your publishing eligibility. You still choose when to make your profile public.</p></div></div>{!profile.isCompleteForPublishing ? <div className="mt-4 rounded-lg bg-amber-50 p-3 text-sm text-amber-900"><CircleAlert className="mr-1 inline" size={16} />Complete your photo, specialization, bio, fee, experience, and license number before verification.</div> : locked ? <p className="mt-4 text-sm text-rose-800">Publishing is unavailable while this profile is under moderation or deleted.</p> : profile.verificationStatus !== 'paid' ? <div className="mt-4"><p className="text-sm text-slate-700">One-time publishing verification fee: <strong>{fee}</strong></p><button type="button" disabled={checkout.isPending} onClick={() => checkout.mutate()} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white hover:bg-indigo-800 disabled:opacity-60"><CreditCard size={17} />{checkout.isPending ? 'Opening secure checkout...' : 'Pay & Verify'}</button></div> : profile.publicationStatus === 'published' ? <div className="mt-4"><p className="text-sm font-semibold text-emerald-800">Verified and publicly published.</p><button type="button" disabled={publication.isPending} onClick={() => publication.mutate('unpublished')} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-lg border border-slate-300 px-4 text-sm font-semibold text-slate-800 disabled:opacity-60"><EyeOff size={17} />Unpublish profile</button></div> : <div className="mt-4"><p className="text-sm font-semibold text-emerald-800">Verification complete. Your profile is still private.</p><button type="button" disabled={publication.isPending} onClick={() => publication.mutate('published')} className="mt-3 inline-flex min-h-11 items-center gap-2 rounded-lg bg-emerald-700 px-4 text-sm font-semibold text-white hover:bg-emerald-800 disabled:opacity-60"><Eye size={17} />Publish profile</button></div>}{message && <p role="alert" className="mt-3 text-sm text-rose-700">{message}</p>}</section>
}
