import { useQuery } from '@tanstack/react-query'
import { BriefcaseBusiness, Languages, MapPin, ShieldCheck } from 'lucide-react'
import { useLocation, useNavigate, useParams, Link } from 'react-router-dom'
import { useState } from 'react'
import { getPublicLawyer } from '../../api/lawyerDiscoveryApi'
import { getMyHiringRequests } from '../../api/hiringRequestApi'
import { ErrorState } from '../../components/common/QueryFeedback'
import AvailabilityBadge from '../../components/lawyers/AvailabilityBadge'
import { getApiErrorMessage } from '../../utils/apiError'
import { useAuth } from '../../auth/useAuth'
import HireModal from '../../components/lawyers/HireModal'
import LawyerComments from '../../components/lawyers/LawyerComments'
import { getMyComments } from '../../api/commentApi'

function DetailSkeleton() { return <div className="grid gap-8 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><div className="aspect-[4/5] animate-pulse rounded-2xl bg-slate-200" /><div className="space-y-4"><div className="h-5 w-28 animate-pulse rounded bg-slate-200" /><div className="h-10 w-3/4 animate-pulse rounded bg-slate-200" /><div className="h-24 animate-pulse rounded bg-slate-200" /></div></div> }

export default function LawyerDetailsPage() {
  const { lawyerId } = useParams(); const { user, isAuthenticated } = useAuth(); const location = useLocation(); const navigate = useNavigate(); const [modalOpen, setModalOpen] = useState(false); const [photoFailed, setPhotoFailed] = useState(false)
  const lawyerQuery = useQuery({ queryKey: ['public-lawyer', lawyerId], queryFn: () => getPublicLawyer(lawyerId) })
  const role = user?.role?.trim().toLowerCase(); const myRequests = useQuery({ queryKey: ['hiring-requests', 'mine'], queryFn: getMyHiringRequests, enabled: role === 'user' })
  const myComments = useQuery({ queryKey: ['comments', 'mine'], queryFn: getMyComments, enabled: role === 'user' })
  if (lawyerQuery.isLoading) return <DetailSkeleton />
  if (lawyerQuery.isError) { const isMissing = lawyerQuery.error?.response?.status === 404; return <ErrorState message={isMissing ? 'This lawyer profile is not publicly available.' : getApiErrorMessage(lawyerQuery.error)} onRetry={isMissing ? undefined : () => lawyerQuery.refetch()} /> }
  const lawyer = lawyerQuery.data; const joined = new Intl.DateTimeFormat('en', { month: 'long', year: 'numeric' }).format(new Date(lawyer.joinedAt)); const existing = myRequests.data?.find((item) => item.lawyerProfileId === lawyer.id)
  const existingLabel = existing?.paymentStatus === 'paid' ? 'Request accepted and paid' : existing?.status === 'accepted' ? 'Request accepted — payment is available now' : existing?.status === 'rejected' ? 'Request rejected' : 'Request pending lawyer review'
  const hireArea = !isAuthenticated ? <button type="button" onClick={() => navigate('/login', { state: { from: location } })} className="min-h-11 rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white">Login to hire</button> : role !== 'user' ? <p className="text-sm font-semibold text-slate-700">Only a normal user account can send a hiring request.</p> : myRequests.isLoading ? <button type="button" disabled className="min-h-11 rounded-lg bg-slate-300 px-4 text-sm font-semibold text-slate-600">Checking request status…</button> : myRequests.isError ? <button type="button" onClick={() => myRequests.refetch()} className="min-h-11 rounded-lg border border-rose-200 px-4 text-sm font-semibold text-rose-700">Retry request status</button> : existing ? <div className="space-y-2"><p className="text-sm font-semibold text-indigo-800">{existingLabel}</p>{existing.status === 'accepted' && existing.paymentStatus !== 'paid' && <Link to="/dashboard/user/hiring-history" className="inline-flex min-h-11 items-center rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white">Go to my hiring requests</Link>}</div> : lawyer.availability === 'busy' ? <button type="button" disabled className="min-h-11 rounded-lg bg-slate-300 px-4 text-sm font-semibold text-slate-600">Currently Busy</button> : <button type="button" onClick={() => setModalOpen(true)} className="min-h-11 rounded-lg bg-indigo-700 px-4 text-sm font-semibold text-white hover:bg-indigo-800">Hire lawyer</button>
  const canComment = role === 'user' && myRequests.data?.some((item) => item.lawyerProfileId === lawyer.id && item.status === 'accepted' && item.paymentStatus === 'paid')
  const hasComment = myComments.data?.some((item) => item.lawyerProfileId === lawyer.id)
  return <><article className="grid gap-8 lg:grid-cols-[minmax(0,0.82fr)_minmax(0,1.18fr)]"><div className="grid aspect-[4/5] overflow-hidden rounded-2xl bg-slate-100"><div className="col-start-1 row-start-1 grid place-items-center text-4xl font-bold text-indigo-700">{lawyer.fullName.slice(0, 2).toUpperCase()}</div>{lawyer.professionalPhotoUrl && !photoFailed && <img src={lawyer.professionalPhotoUrl} alt={`Portrait of ${lawyer.fullName}`} className="col-start-1 row-start-1 h-full w-full object-cover" onError={() => setPhotoFailed(true)} />}</div><div><div className="flex flex-wrap items-center gap-3"><AvailabilityBadge availability={lawyer.availability} /><span className="text-sm text-slate-500">Joined {joined}</span></div><p className="mt-5 text-sm font-semibold uppercase tracking-[0.16em] text-indigo-700">{lawyer.specialization}</p><h1 className="mt-2 text-4xl font-semibold tracking-tight text-slate-950">{lawyer.fullName}</h1>{lawyer.additionalSpecializations.length > 0 && <div className="mt-4 flex flex-wrap gap-2">{lawyer.additionalSpecializations.map((item) => <span key={item} className="rounded-full bg-indigo-50 px-3 py-1 text-sm text-indigo-800">{item}</span>)}</div>}<p className="mt-6 max-w-2xl whitespace-pre-line leading-7 text-slate-700">{lawyer.bio}</p><dl className="mt-8 grid gap-4 border-y border-slate-200 py-6 sm:grid-cols-2"><div><dt className="text-sm text-slate-500">Consultation fee</dt><dd className="mt-1 text-xl font-semibold text-slate-950">${(lawyer.consultationFeeMinor / 100).toFixed(2)} USD</dd></div><div><dt className="text-sm text-slate-500">Experience</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-slate-950"><BriefcaseBusiness size={18} />{lawyer.experienceYears} years</dd></div><div><dt className="text-sm text-slate-500">License</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-slate-950"><ShieldCheck size={18} />{lawyer.licenseNumber}</dd></div><div><dt className="text-sm text-slate-500">Location</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-slate-950"><MapPin size={18} />{lawyer.location || 'Not listed'}</dd></div><div className="sm:col-span-2"><dt className="text-sm text-slate-500">Languages</dt><dd className="mt-1 flex items-center gap-2 font-semibold text-slate-950"><Languages size={18} />{lawyer.languages.length ? lawyer.languages.join(', ') : 'Not listed'}</dd></div></dl><div className="mt-8 rounded-xl bg-slate-100 p-4"><p className="font-semibold text-slate-900">Send a hiring request</p><p className="mt-1 text-sm text-slate-600">The lawyer must accept before payment becomes available.</p><div className="mt-4">{hireArea}</div></div></div></article><LawyerComments profileId={lawyer.id} canComment={canComment} hasComment={hasComment} isAuthenticated={isAuthenticated} role={role} />{modalOpen && <HireModal lawyer={lawyer} onClose={() => setModalOpen(false)} />}</>
}
