import { useEffect } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { CheckCircle2, Clock3, XCircle } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { getPaymentStatus } from '../../api/paymentApi'
import { ErrorState } from '../../components/common/QueryFeedback'

export default function PaymentReturnPage({ cancelled = false, sslcommerz = false, failed = false }) {
  const [params] = useSearchParams(); const transactionId = params.get('transactionId') ?? params.get('txn'); const client = useQueryClient()
  const payment = useQuery({ queryKey: ['payment-status', transactionId], queryFn: () => getPaymentStatus(transactionId), enabled: Boolean(transactionId), refetchInterval: (query) => !cancelled && !failed && query.state.data?.transactionStatus !== 'paid' ? 2500 : false, retry: 2 })
  const isSsc = sslcommerz || payment.data?.gateway === 'sslcommerz'; const paid = payment.data?.transactionStatus === 'paid'; const hiring = payment.data?.type === 'hiring_fee'
  const destination = hiring ? '/dashboard/user/hiring-history' : '/dashboard/lawyer/manage-legal-profile'
  const gatewayLabel = isSsc ? 'bKash / Nagad (SSLCommerz)' : 'card payment'
  useEffect(() => { if (paid) { client.invalidateQueries({ queryKey: ['hiring-requests'] }); client.invalidateQueries({ queryKey: ['payments', 'mine'] }); client.invalidateQueries({ queryKey: ['public-lawyers'] }); client.invalidateQueries({ queryKey: ['top-lawyers'] }) } }, [client, paid])
  if (!transactionId) return <ErrorState message="This payment return link is incomplete." />
  if (payment.isLoading) return <section className="mx-auto max-w-xl rounded-2xl border border-slate-200 dark:border-[#1c3050] bg-white dark:bg-[#0c1728] p-8 text-center"><Clock3 className="mx-auto animate-pulse text-indigo-700" size={40} /><h1 className="mt-4 text-2xl font-semibold dark:text-[#ece5d6]">Checking your payment</h1><p className="mt-3 text-slate-600 dark:text-[#a8bbcc]">We are checking the verified server status of your {gatewayLabel}.</p></section>
  if (payment.isError) return <ErrorState message="We could not confirm this payment yet. Return to your dashboard and check again shortly." />
  if ((cancelled || failed) && !paid) return <section className="mx-auto max-w-xl rounded-2xl border border-amber-200 dark:border-amber-900/50 bg-amber-50 dark:bg-amber-950/30 p-8 text-center"><XCircle className="mx-auto text-amber-700 dark:text-amber-300" size={40} /><h1 className="mt-4 text-2xl font-semibold text-slate-950 dark:text-[#ece5d6]">{failed ? 'Your payment failed' : 'Payment was not confirmed'}</h1><p className="mt-3 text-slate-700 dark:text-[#ece5d6]">No payment was marked complete. You can retry with {gatewayLabel} or card whenever you're ready — both options are on your hiring requests page.</p><Link to={destination} className="mt-6 inline-flex rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{hiring ? 'Return to my hiring requests' : 'Return to legal profile'}</Link></section>
  return <section className="mx-auto max-w-xl rounded-2xl border border-slate-200 dark:border-[#1c3050] bg-white dark:bg-[#0c1728] p-8 text-center"><>{paid ? <CheckCircle2 className="mx-auto text-emerald-600" size={42} /> : <Clock3 className="mx-auto animate-pulse text-indigo-700" size={42} />}</><h1 className="mt-4 text-2xl font-semibold text-slate-950 dark:text-[#ece5d6]">{paid ? (hiring ? 'Hiring payment successful' : 'Verification successful') : 'Payment is still being confirmed'}</h1><p className="mt-3 text-slate-600 dark:text-[#a8bbcc]">{paid ? (hiring ? 'Your hiring request is now marked paid.' : 'Your profile remains private until you explicitly publish it.') : 'Do not submit another payment. This page checks the verified server status automatically.'}</p><Link to={destination} className="mt-6 inline-flex rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-semibold text-white">{hiring ? 'Return to my hiring requests' : 'Return to legal profile'}</Link></section>
}
